#   Makefile for SPY.COM
#
#   History
#   -------
#   Created: 05-Jun-1992 by Jeff Parsons
#

.SUFFIXES:
.SUFFIXES: .c .asm .h .inc .obj .lst .sys .exe .com .map .sym

INCLUDE=
LIB=
PATH=

!IFNDEF PS2
DEFFLAGS=-DDEBUG $(FLAGS)
!ELSE
DEFFLAGS=-DPS2 -DDEBUG $(FLAGS)
!ENDIF

!IFNDEF ASM
ASM=tools\ml
FIXASM=tools\fixasm
!ENDIF

!IFNDEF C32
C32=tools\cl3232 -d2omf
!ENDIF

!IFNDEF LINK
LINK=tools\link
!ENDIF

!IFNDEF H2INC
H2INC=tools\h2inc
!ENDIF


{h\}.h{inc\}.inc:
    $(H2INC) -t -s h\types.h h\$(<B).h -o $@


.asm.com:
    $(ASM) -nologo -AT -Cp -Iinc -W3 -Zm $(DEFFLAGS) -Fm -Fo$@ $(<B).asm

.asm{obj\}.obj:
    $(ASM) -nologo -c -Cp -Iinc -W3 -Zm $(DEFFLAGS) -Fm -Fo$@ $(<B).asm

{lib\}.asm{obj\}.obj:
    $(ASM) -nologo -c -Cp -Iinc -W3 -Zm $(DEFFLAGS) -Fm -Fo$@ lib\$(<B).asm

.asm.lst:
    $(ASM) -nologo -c -Cp -Iinc -W3 -Zm $(DEFFLAGS) -Fm -Fonul -Fl$@ $(<B).asm

{lib\}.asm.lst:
    $(ASM) -nologo -c -Cp -Iinc -W3 -Zm $(DEFFLAGS) -Fm -Fonul -Fl$@ lib\$(<B).asm


.c{obj\}.obj:
    $(C32) -nologo -c -Oas -Gs -Ih -W3 -Zp $(DEFFLAGS) -Fonul -Faobj\$(<B).asm $(<B).c
    $(FIXASM) obj\$(<B).asm
    $(ASM) -nologo -c -Cp -Ih -W3 -Zm $(DEFFLAGS) -Fm -Fo$@ obj\$(<B).asm

{lib\}.c{obj\}.obj:
    $(C32) -nologo -c -Oas -Gs -Ih -W3 -Zp $(DEFFLAGS) -Fo$@ lib\$(<B).c

.c.lst:
    $(C32) -nologo -c -Oas -Gs -Ih -W3 -Zp $(DEFFLAGS) -Fonul -Fc$@ $(<B).c

{lib\}.c.lst:
    $(C32) -nologo -c -Oas -Gs -Ih -W3 -Zp $(DEFFLAGS) -Fonul -Fc$@ lib\$(<B).c


# Default target(s)

default:        spy.com reboot.com


h\all.h:	h\types.h h\386.h h\387.h \
                h\ems.h h\bios.h h\dos.h h\debug.h \
                h\globals.h h\x86.h h\lib.h \
                h\pic.h h\timer.h h\kbd.h h\disk.h \
		h\cmos.h h\video.h h\com.h

inc\all.inc:    inc\types.inc inc\386.inc inc\387.inc \
                inc\ems.inc inc\bios.inc inc\dos.inc inc\debug.inc \
                inc\globals.inc inc\x86.inc inc\lib.inc \
                inc\pic.inc inc\timer.inc inc\kbd.inc inc\disk.inc \
		inc\cmos.inc inc\video.inc inc\com.inc


obj\386init.obj:    386init.asm inc\all.inc

obj\386trap.obj:    386trap.asm inc\all.inc

obj\v86int.obj:     v86int.asm  inc\all.inc

obj\v86io.obj:      v86io.asm   inc\all.inc

obj\main.obj:       main.c      h\all.h

obj\memmgr.obj:     memmgr.c    h\all.h

obj\vidmgr.obj:     vidmgr.c    h\all.h

obj\vidsave.obj:    vidsave.asm inc\all.inc

obj\comio.obj:      comio.asm   inc\all.inc

obj\x86debug.obj:   x86debug.c  h\all.h

obj\intparse.obj:   intparse.c  h\all.h

obj\dosdump.obj:    dosdump.c   h\all.h

obj\printf.obj:     lib\printf.c h\all.h

obj\gets.obj:       lib\gets.c  h\all.h

obj\sprintf.obj:    lib\sprintf.c h\types.h h\lib.h

obj\string.obj:     lib\string.c h\types.h h\lib.h


spy.com:        obj\386init.obj obj\386trap.obj obj\v86int.obj obj\v86io.obj \
                obj\main.obj obj\memmgr.obj obj\vidmgr.obj obj\vidsave.obj \
                obj\comio.obj obj\x86debug.obj obj\intparse.obj obj\dosdump.obj \
                obj\printf.obj obj\gets.obj obj\sprintf.obj obj\string.obj
    $(LINK) @<<
$**
$@ /tiny /nod /map;
<<


reboot.com: obj\reboot.obj
    $(LINK) @<<
$**
$@ /tiny /nod /map;
<<
